camera:
  deviceid: 0
  # windows 640x480
  # RaspberryPi  1920*1080
  width: 640
  height: 480
window:
  enable: true
  title: Motion Window
  # windows 640x480
  # RaspberryPi  1920*1080
  width: 640
  height: 480
web:
  enable: true
  host: 0.0.0.0
  post: 9000
video:
  enable: true
  fps: 25
  prefix: motion
