camera:
  deviceid: 0
  # windows 640x480
  # RaspberryPi  3280x2464
  # check camera by "raspistill -v -n -t 2000 -o shot.jpg"
  #
  width: 640
  height: 480
window:
  enable: true
  title: Motion Window
  width: 1024
  height: 768
web:
  enable: true
  host: 0.0.0.0
  post: 9000
video:
  enable: true
  fps: 25
  prefix: motion
